# This workflow will run tests using node and then publish a package to NPM Packages when a release is created

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: "Install dependencies"
        run: npm ci

      - name: "Check linting"
        run: npm run lint

      - name: "Start testing the project"
        run: npm run test

      - name: "Build the project"
        run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: "Install dependencies"
        run: npm ci

      - name: "Publish to GitHub Package Registry"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-npm-with-scope:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: "Install dependencies"
        run: npm ci

      - name: "Add scope to the package name"
        run: node ./scripts/rename-package.js

      - name: "Publish to GitHub Package Registry"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: "Remove scope from the package name"
        run: node ./scripts/rename-package.js

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: "Install dependencies"
        run: npm ci

      - name: "Add scope to the package name"
        run: node ./scripts/rename-package.js

      - name: "Publish to GitHub Package Registry"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Remove scope from the package name"
        run: node ./scripts/rename-package.js
