name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      # check npm version is the same as development environment
      - name: "npm version is:"
        run: npm -v

      - name: "check the current files"
        run: ls -la

      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run lint
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
